version: '3'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql-chat
    environment:
      - DB_HOST=mysql-chat
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}
      - WELCOME_MESSAGE=${WELCOME_MESSAGE}
    networks:
      - chat-network

  mysql-chat:
    image: mysql:8.1.0
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - ${MYSQL_HOST_PORT}:3306
    volumes:
      - db_chat_data:/var/lib/mysql
    networks:
      - chat-network

  web:
    image: nginx:1.25.2-alpine-slim
    restart: no
    ports:
      - ${NGINX_HOST_PORT}:80
    volumes:
      - ./web:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - chat-network

networks:
  chat-network:

volumes:
  db_chat_data: